global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "proxy-gateway"
    static_configs:
      - targets: ["proxy-gateway:7777"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "node-registration"
    static_configs:
      - targets: ["node-registration:8001"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "customer-api"
    static_configs:
      - targets: ["customer-api:8002"]
    metrics_path: /metrics
    scrape_interval: 30s